### ISSUE TITLE
Hour after Minus - Hour is 00 again

### ISSUE THREAD

**Issue by kokoye2007** [fossasia/open-event-server#5963] opened 2019-05-28 13:38 UTC
**Describe the bug**
HH:MM is not working

**To Reproduce**
in event time
1. HH choose
2. MM choose
3. HH is 00 again

**Comment by kushthedude** [comment] 2019-05-28 23:00
@iamareebjamal the following issue is of FE and already the work has been started on it , It can be closed .

**Comment by iamareebjamal** [comment] 2019-05-29 09:18
Please mention the issue number

**Comment by kushthedude** [comment] 2019-05-29 22:32
See https://github.com/fossasia/open-event-frontend/issues/2077 and https://github.com/fossasia/open-event-frontend/issues/2366

**Comment by iamareebjamal** [comment] 2019-05-30 07:01
Duplicate of above issues. Hence, closing

**Comment by kushthedude** [comment] 2019-06-05 10:49
@iamareebjamal Since the following is a FE issue ,Closing it henceforth

**Closed by kushthedude** 2019-06-05 10:49 UTC
Labels: needs-info
