### ISSUE TITLE
Creating Identifier for Ticket of different users

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-server#5701] opened 2019-03-21 08:50 UTC
**Is your feature request related to a problem? Please describe.**
I have taken a look into the Open Event API Server website, and I find a problem, please correct me if there is anything wrong.

In Tickets/List Tickets for an Order, it returns a list of tickets under one order by ```/v1/orders/{order_identifier}/tickets```. So the problem in here is that although there is an indentifier for an order, there are no identifier for tickets inside one order. For instance, if I book an order with 3 tickets, those 3 tickets cannot be distinguished as they doesn't have any kind of ticket identifier but only share the same order identifier.

In the Ticket section, a ticket in here contains parameters like name (ticket name), type, description, price,... but it doesn't contain any parameters about the person holding the ticket so I assume for now it is not possible to distinguish between any ticket holders who have the same ticket.

**Describe the solution you'd like**
For now, it seems kind of a big problem to me and I'm not working in open-event-server so I don't have any detailed solutions. But I would suggest taking a look back at what I have written above to clarify if this is truly a problem. If it is, I would suggest creating a new UserTicket object in the server to solve that Ticket problem.

**Comment by mrsaicharan1** [comment] 2019-03-21 08:52
Would definitely like to take a look into implementing individual
identifiers. Will take it up

**Comment by shreyanshdwivedi** [comment] 2019-03-21 08:54
@CosmicCoder96 can you please suggest a way to tackle this? According to me, we can have an identifier for ticket also. And we can view separate tickets like `<order id>/<ticket id>`. For beginning we can use ticket number in place of ticket id e.g. if there are 3 tickets, we can have 1, 2, 3 as ticket id.

**Comment by mrsaicharan1** [comment] 2019-03-21 09:09
@shreyanshdwivedi I think that would be a good idea. Alternatively, we could also assign each ticket a uuid and represent them as `<order_id>/<ticket_uuid>`

**Comment by iamareebjamal** [comment] 2019-03-21 09:16
Right now we match an identifier with an attendee. We need this mapping in order to enable scanning in the orga app. This should be taken into account while changing the implementation

**Comment by iamareebjamal** [comment] 2019-03-21 09:17
Prefer uuid over integers always for publicly exposed keys

**Comment by CosmicCoder96** [comment] 2019-03-21 09:30
A question @iamareebjamal Same ticket is purchased by various users. So let's say a ticket has id 4.

It is a part of several orders: let's say of order id's : 1,2,3,4,5,6

on using orders/<identifier>/tickets
we get the list of tickets that order has in it, let's say tan order of id 2 has tickets with ids: [4,5,6]

What exactly do we mean by individual identifiers? No separate instance of a ticket is created for a particular order. Hence, [4,5,6] are in fact the only identifiers existing in the system.
So orders/tickets/<uuid> will ultimately point to /tickets/4. What would be its utility?
 I think this was by design, and not an oversight. Though, I wasn't involved in the creation of the orders API. Thoughts?

**Comment by iamareebjamal** [comment] 2019-03-21 09:34
As per my understanding. A user creates an order which can have multiple attendees. And each attendee has a different ticket? If not so, then this function is not needed. But if there are multiple tickets in an order, then we need to identify them individually. Also if there's only one ticket instance per order, the issue is invalid but it's a limitation. What if you ordered a ticket for yourself and me and I arrive late at the event. You can't enter until I arrive and this requires human assistance to verify that all attendees under an order are checked in at the same time. Please correct me if I'm wrong

**Comment by iamareebjamal** [comment] 2019-03-21 09:37
I think we have a misunderstanding about tickets. I misunderstood what was meant by a ticket. You are right. Same ticket identifier will be used by many orders. I confused it with a physical ticket rather than a collective term we use in the API. My final question will be, do we have a way to individually identify attendees, e.g. if an order has 4 attendees. Can we identify them each individually using the QR code. And do they have different downloadable/printable tickets?

**Comment by CosmicCoder96** [comment] 2019-03-21 09:42
> My final question will be, do we have a way to individually identify attendees, e.g. if an order has 4 attendees. Can we identify them each individually using the QR code. And do they have different downloadable/printable tickets?

Talking strictly in terms of the server's perspective, (I am not sure if the FE or the app make use of it) it is possible. In the `TicketHolder` model (attendee) there is a field called `ticket_id` which is a foreign key corresponding to the tickets table. Hence, each attendee is aware of which ticket was meant for him.

**Comment by CosmicCoder96** [comment] 2019-03-21 09:46
okay sounds good @iamareebjamal thanks!

**Closed** 2019-03-21 09:46 UTC

**Comment by iamareebjamal** [comment] 2019-03-21 09:48
@anhanh11001 I hope this answers your questions about what ticket means in terms of open event API. You can check out orga app's code to see what is used to identify individual attendees
