### ISSUE TITLE
import event is broken

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-server#5690] opened 2019-03-16 07:38 UTC
**Describe the bug**

When trying to import an event in a fresh database , it is throwing an error which states.

**To Reproduce**
1. Create an event and export it, you should get a zip folder like : `event<id>.zip`
2. Drop current database and create fresh database
3. Try importing this event as an admin

**Expected behavior**
It should've imported without any error.

**Stacktrace**

#### Celery Stacktrace
```
[2019-03-16 11:21:32,267: ERROR/MainProcess] Task import.event[1e476cd6-d95a-4820-8d01-58c3b022dd0b] raised unexpected: OperationalError('(psycopg2.OperationalError) terminating connection due to administrator command\nserver closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n',)
Traceback (most recent call last):
  File "/home/uddeshya/venv/lib/python3.5/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/uddeshya/Desktop/mySetup/open-event-server/app/api/helpers/request_context_task.py", line 46, in __call__
    result = call()
  File "/home/uddeshya/Desktop/mySetup/open-event-server/app/api/helpers/request_context_task.py", line 32, in <lambda>
    call = lambda: super(RequestContextTask, self).__call__(*args, **kwargs)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/uddeshya/Desktop/mySetup/open-event-server/app/api/helpers/tasks.py", line 145, in import_event_task
    user = db.session.query(User).filter_by(email=email).first()
  File "/home/uddeshya/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2755, in first
    ret = list(self[0:1])
  File "/home/uddeshya/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
    return list(res)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/uddeshya/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/uddeshya/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/uddeshya/venv/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) terminating connection due to administrator command
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
 [SQL: 'SELECT users.deleted_at AS users_deleted_at, users.id AS users_id, users._email AS users__email, users._password AS users__password, users.facebook_id AS users_facebook_id, users.facebook_login_hash AS users_facebook_login_hash, users.reset_password AS users_reset_password, users.salt AS users_salt, users.avatar_url AS users_avatar_url, users.tokens AS users_tokens, users.first_name AS users_first_name, users.last_name AS users_last_name, users.details AS users_details, users.contact AS users_contact, users.facebook_url AS users_facebook_url, users.twitter_url AS users_twitter_url, users.instagram_url AS users_instagram_url, users.google_plus_url AS users_google_plus_url, users.original_image_url AS users_original_image_url, users.thumbnail_image_url AS users_thumbnail_image_url, users.small_image_url AS users_small_image_url, users.icon_image_url AS users_icon_image_url, users.is_super_admin AS users_is_super_admin, users.is_admin AS users_is_admin, users.is_sales_admin AS users_is_sales_admin, users.is_marketer AS users_is_marketer, users.is_verified AS users_is_verified, users.was_registered_with_order AS users_was_registered_with_order, users.last_accessed_at AS users_last_accessed_at, users.created_at AS users_created_at \nFROM users \nWHERE users._email = %(_email_1)s \n LIMIT %(param_1)s'] [parameters: {'_email_1': 'uds@email.com', 'param_1': 1}]

```
**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS] Ubuntu 16.04 LTS
 - Python Version [e.g. `3.5`, `3.6`] 3.5

**Additional context**

I would like to work on it once it's confirmed by another triage

**Comment by uds5501** [comment] 2019-03-16 07:40
On frontend : 
![image](https://user-images.githubusercontent.com/21087061/54472334-d735ec00-47ec-11e9-84c5-71338ffae433.png)

**Comment by iamareebjamal** [comment] 2019-03-16 07:53
Check the error again. I think it is a one time error

**Comment by uds5501** [comment] 2019-03-16 08:12
@iamareebjamal I tried it again in the same sequence of events, it gives the same error

**Comment by iamareebjamal** [comment] 2019-03-16 08:23
OK. Strange

**Comment by mrsaicharan1** [comment] 2019-03-21 04:57
I suppose this is a duplicate of #4613

**Comment by uds5501** [comment] 2019-03-21 05:32
@mrsaicharan1 the error messeges are different

**Comment by kushthedude** [comment] 2019-06-05 11:16
@uds5501 I think they are working now , Are we good to close ?

**Comment by uds5501** [comment] 2019-06-05 11:19
@kushthedude yes. close this

**Closed** 2019-06-05 11:19 UTC
