### ISSUE TITLE
Event Transfer: Current owner to be downgraded to Organiser, no duplicate owner role invites allowed

### ISSUE THREAD

**Issue by MeghalBisht** [fossasia/open-event-server#7946] opened 2021-05-11 18:37 UTC
**Is your feature request related to a problem? Please describe.**

When a user transfers the event to a user A. [role - owner]
And then again transfers it to user B [role - owner]
So, if A accepts the invite - A becomes the owner of the event. 
If B accepts the invite as well, A is removed as owner and B is now the owner [Non-ideal case]
The event is removed from the user who started the transfer process.

**Describe the solution you'd like**

Expected - 1) Only one person can be invited to be the owner. If the current owner sends out a new invite to someone else a message should pop up “Sending an invite to another user will void all previous owner invites.”
2) Current owner should be downgraded to “organiser” when another person accepts the “invite to be an owner”.

Screenshots -
2 users having role - Owner
![Screenshot from 2021-05-12 00-08-35](https://user-images.githubusercontent.com/61330148/117867637-3e109c00-b2b6-11eb-8a3b-96ef1f2b212e.png)

**Comment by progmatic-99** [comment] 2021-06-02 12:35
I am not able to reproduce this.
When I transferred the owner role to a account that was not in the organizer list, the transfer happened as is needed, i.e, the current owner became organizer.
But when I tried to transfer the owner role to an existing organizer, it showed an error: ```Role invite has already been sent.````

**Comment by MeghalBisht** [comment] 2021-06-02 13:09
> When I transferred the owner role to a account that was not in the organizer list, the transfer happened as is needed, i.e, the current owner became organizer.

The current owner is removed and NOT downgraded to organizer once the transfer is successful. However, we need to downgrade him to an organizer now instead.

> But when I tried to transfer the owner role to an existing organizer, it showed an error: `Role invite has already been sent.`

That is because the user is already having a role of organizer, in order to now make him a owner, you need to delete the previous role and then initiate the transfer of event.

**Closed** 2021-07-05 12:05 UTC
Labels: codeheat, enhancement
