### ISSUE TITLE
Saving speaker profile does not work

### ISSUE THREAD

**Issue by nyc-pm** [fossasia/open-event-server#5470] opened 2018-12-15 14:29 UTC
There is an issue with saving a new speaker profile.

I have submitted all the details but it has trouble saving the information.

**Comment by rastermann** [comment] 2018-12-15 16:40
Same for me... tried multiple times.

**Comment by iamareebjamal** [comment] 2018-12-15 16:44
Can you please share the request and response of the failed attempt?

**Comment by rastermann** [comment] 2018-12-16 12:44
Well as it's https - no. i can't. i can't sniff it. but the response is a pretty useless error page that says:

"We seem to be having some issues on our side. Please report any errors or bug to our Issue tracker on GitHub."

You should have these logs on your server side... :)

**Comment by iamareebjamal** [comment] 2018-12-16 15:14
To clarify, you faced this issue using the API or the frontend application? Did you use eventyay.com or api.eventyay.com?

**Comment by iamareebjamal** [comment] 2018-12-16 18:11
That is legacy project. @nyc-pm Did you also face the issue on eventyay.com. If so, we can move it to the legacy project.

**Comment by rastermann** [comment] 2018-12-16 20:14
well. the website does say to report the issue on github right to this link... :)

**Comment by iamareebjamal** [comment] 2018-12-16 20:47
Yes, because we moved the legacy site to a different repository and host the next-gen API in this one. Sorry for the inconvenience

**Comment by hpdang** [comment] 2018-12-17 22:40
@rastermann @TScottJ thank you for reporting. A workaround, create a new account with the same email, it will overwrite the old profile. @rastermann I updated your profile in the system based on what I know, you can log-in and edit it now.

**Comment by rastermann** [comment] 2018-12-18 22:06
Thanks Hong Phuc. Awesome to see you  here! You've indeed edited - but I can't make any changes. Still has an error. :( Should I try make a new account then?

**Comment by miphilomath** [comment] 2018-12-19 18:47
Creating a new account is not helping either. Should I email my talk proposal somewhere?

I am attaching the screen shot of the error, but it is not very descriptive.
![image](https://user-images.githubusercontent.com/26297035/50241114-a6603980-03ec-11e9-9d3c-f2b7ccc823fa.png)

**Comment by rastermann** [comment] 2018-12-20 10:08
That's just what I get too - I see a new account is not a solution, but I was able to submit a talk proposal. I just couldn't edit my speaker bio/details at all. Perhaps it's time that this reverts to email as the deadline is in 2 days for 2019 FOSSASIA submissions.

**Comment by mrsaicharan1** [comment] 2019-01-15 11:08
@rastermann  Could you explain how to reproduce the error so that it would be easy to get around it?

**Comment by rastermann** [comment] 2019-01-15 11:32
Literally fill in the form (speaker profile), submit it, then get that error. Happens every single time for me regardless of content of the form it seems.

**Comment by mrsaicharan1** [comment] 2019-01-15 11:42
I can see that even the form isn't opening now. @rastermann, you are referring to this link right? https://2019.fossasia.org/speaker-registration

**Comment by uds5501** [comment] 2019-03-20 16:41
@iamareebjamal I guess we can close this issue now?

**Closed** 2019-03-20 19:58 UTC
