### ISSUE TITLE
Missing exception handling for `test_has_access`

### ISSUE THREAD

**Issue by invinciblycool** [fossasia/open-event-server#4529] opened 2017-11-03 14:30 UTC
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
While running tests with dredd as well as running unittests an exception is returned for the test `test_has_access`
Here is the traceback.
https://travis-ci.org/fossasia/open-event-orga-server/builds/296800782#L4913

**Expected behavior:**
Exception should be handled.
**Steps to reproduce:**
Run tests either with dredd or normally.

**Comment by invinciblycool** [comment] 2017-11-03 14:31
If confirmed, I would like to work on it.

**Comment by raju249** [comment] 2017-11-25 11:20
@invinciblycool 
Are you working on this or its available ?

**Comment by poush** [comment] 2017-11-25 12:15
I checked build log and didn't find any reasons for TypeError on first look. Since permission manager's `has_access` doesn't create any SQL operations, therefore, I guess something on `test_request_context` causing it. Try to debug if something comes up.

**Comment by raju249** [comment] 2017-11-25 13:40
Claiming this!

**Comment by raju249** [comment] 2017-11-26 06:24
@poush Any idea of how to recreate this issue locally ?
I tried running the particular test case using nosetests. But that didn't work out. All the tests failed, may be there is some config for running those tests that has to be done before hand.
Let me know how did you reproduce it locally. 
Thanks :smile:

**Comment by poush** [comment] 2017-11-26 12:07
Make sure you are following what written under Testing in ReadME. If you are able to run server locally and follow things therein readme. I don't think there will be any issue. Let me know if occurs any.

**Comment by raju249** [comment] 2017-11-26 12:13
Sure!

**Comment by raju249** [comment] 2017-11-29 13:51
I tried using the steps in testing readme.
Here is stack trace I get (I ran only 1 test)
```
ProgrammingError: (psycopg2.ProgrammingError) permission denied for relation roles
 [SQL: 'SELECT roles.id AS roles_id, roles.name AS roles_name, roles.title_name AS roles_title_name \nFROM roles \nWHERE roles.title_name = %(title_name_1)s AND roles.name = %(name_1)s \n LIMIT %(param_1)s'] [parameters: {'title_name_1': 'Organizer', 'name_1': 'organizer', 'param_1': 1}]
```

**Comment by raju249** [comment] 2017-11-29 13:55
I also gave the privileges on all tables to test user.

**Comment by bhaveshAn** [comment] 2018-07-24 17:51
Current builds are passing https://travis-ci.org/fossasia/open-event-server/builds
https://travis-ci.org/fossasia/open-event-server/builds/407714059

Hence closing this one. Feel free to reopen if it persists.

**Closed** 2018-07-24 17:51 UTC
