### ISSUE TITLE
Not able to import modules from 'elasticsearch_dsl

### ISSUE THREAD

**Issue by Aju100** [fossasia/open-event-server#6614] opened 2019-11-24 03:03 UTC
** Not able to import modules from 'elasticsearch_dsl **
I am unable to run create_db.py to setup this [repository.]

**To Reproduce**
1. Go to 'clone the repository and activate virtualenv '
2. setup database and package
3. run python3 create_db.py

`Traceback (most recent call last):
  File "create_db.py", line 7, in <module>
    from app import current_app
  File "/home/aju/Desktop/flask/open-event-server/app/__init__.py", line 35, in <module>
    from app.api.helpers.jwt import jwt_user_loader
  File "/home/aju/Desktop/flask/open-event-server/app/api/__init__.py", line 1, in <module>
    from app.api.access_codes import AccessCodeList, AccessCodeListPost, AccessCodeDetail, AccessCodeRelationshipRequired, \
  File "/home/aju/Desktop/flask/open-event-server/app/api/access_codes.py", line 5, in <module>
    from app.api.bootstrap import api
  File "/home/aju/Desktop/flask/open-event-server/app/api/bootstrap.py", line 3, in <module>
    from app.api.helpers.permission_manager import permission_manager
  File "/home/aju/Desktop/flask/open-event-server/app/api/helpers/permission_manager.py", line 9, in <module>
    from app.models.event import Event
  File "/home/aju/Desktop/flask/open-event-server/app/models/event.py", line 19, in <module>
    from app.models.search import sync
  File "/home/aju/Desktop/flask/open-event-server/app/models/search/sync.py", line 11, in <module>
    from app.models.search.event import SearchableEvent
  File "/home/aju/Desktop/flask/open-event-server/app/models/search/event.py", line 2, in <module>
    from elasticsearch_dsl import DocType, Integer, Search, Text
ImportError: cannot import name 'DocType' from 'elasticsearch_dsl' (/home/aju/Desktop/flask/lib/python3.7/site-packages/elasticsearch_dsl/__init__.py)
`

**Additional details:**
 - OS:  
   - Distributor ID:	Ubuntu
   - Description:	Ubuntu 19.04
   - Release:	19.04
   - Codename:	disco 
 - Python Version 
    - Python 3.7.3 
    - [GCC 8.3.0] on linux

**Comment by kushthedude** [comment] 2019-11-24 05:12
Not Reproducible, Please mention some more specific instructions.

**Comment by iamareebjamal** [comment] 2019-11-24 07:25
Duplicate of #6560

**Closed by iamareebjamal** 2019-11-24 07:25 UTC

**Comment by Aju100** [comment] 2019-11-25 03:08
@iamareebjamal  still didn't  get the point to setup this repository.

**Comment by iamareebjamal** [comment] 2019-11-25 05:08
Have you pulled the latest changes and reinstalled dependencies
