### ISSUE TITLE
Error 500 in Admin's sales tab

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-server#5713] opened 2019-03-25 14:57 UTC
**Describe the bug**

Error 500 is returned in the Admin's sales tab

**To Reproduce**
1. Go to 'Admin' section.
2. Click on 'Sales' tab.
3. See error.

**Expected behavior**

Should have returned sales data, status code 200. 

**Stacktrace**

```
INFO:werkzeug:127.0.0.1 - - [25/Mar/2019 20:16:13] "GET /v1/admin/sales/by-events?sort=name HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/haider/github-repos/open-event-server/app/__init__.py", line 67, in __call__
    return self.app(environ, start_response)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/haider/github-repos/open-event-server/.venv/src/flask-rest-jsonapi/flask_rest_jsonapi/api.py", line 133, in decorated
    return self.check_permissions(view, view_args, view_kwargs, *args, **kwargs)
  File "/home/haider/github-repos/open-event-server/app/api/helpers/permission_manager.py", line 439, in permission_manager
    return permissions[args[0]](view, view_args, view_kwargs, *args, **kwargs)
  File "/home/haider/github-repos/open-event-server/app/api/helpers/permissions.py", line 45, in decorator
    return fn(*args, **kwargs)
  File "/home/haider/github-repos/open-event-server/app/api/helpers/permission_manager.py", line 38, in is_admin
    return view(*view_args, **view_kwargs)
  File "/home/haider/github-repos/open-event-server/.venv/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/haider/github-repos/open-event-server/.venv/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 68, in dispatch_request
    response = method(*args, **kwargs)
  File "/home/haider/github-repos/open-event-server/.venv/src/flask-rest-jsonapi/flask_rest_jsonapi/decorators.py", line 56, in wrapper
    return func(*args, **kwargs)
  File "/home/haider/github-repos/open-event-server/.venv/src/flask-rest-jsonapi/flask_rest_jsonapi/resource.py", line 155, in get
    result = schema.dump(objects).data
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/marshmallow/schema.py", line 511, in dump
    **kwargs
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/marshmallow/marshalling.py", line 124, in serialize
    for idx, d in enumerate(obj)]
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/marshmallow/marshalling.py", line 124, in <listcomp>
    for idx, d in enumerate(obj)]
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/marshmallow/marshalling.py", line 147, in serialize
    index=(index if index_errors else None)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/marshmallow/marshalling.py", line 68, in call_and_store
    value = getter_func(data)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/marshmallow/marshalling.py", line 141, in <lambda>
    getter = lambda d: field_obj.serialize(attr_name, d, accessor=accessor)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/marshmallow/fields.py", line 252, in serialize
    return self._serialize(value, attr, obj)
  File "/home/haider/github-repos/open-event-server/.venv/lib/python3.6/site-packages/marshmallow/fields.py", line 1201, in _serialize
    return method(obj)
  File "/home/haider/github-repos/open-event-server/app/api/admin_sales/events.py", line 42, in calc_sales
    return summary(obj.orders)
  File "/home/haider/github-repos/open-event-server/app/api/admin_sales/utils.py", line 23, in summary
    return {s: status_summary(orders, s) for s in status_codes}
  File "/home/haider/github-repos/open-event-server/app/api/admin_sales/utils.py", line 23, in <dictcomp>
    return {s: status_summary(orders, s) for s in status_codes}
  File "/home/haider/github-repos/open-event-server/app/api/admin_sales/utils.py", line 13, in status_summary
    'sales_total': sum([o.amount for o in orders if o.status == status]),
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

Will work if someone can please confirm

**Comment by iamareebjamal** [comment] 2019-03-25 16:32
#5706 will fix this

**Comment by iamareebjamal** [comment] 2019-03-25 16:34
Duplicate of #5705

**Closed by iamareebjamal** 2019-03-25 16:34 UTC

**Comment by Haider8** [comment] 2019-03-26 15:43
> #5706 will fix this

@iamareebjamal issue is still there.

**Comment by iamareebjamal** [comment] 2019-03-26 18:39
You haven't run the migrations yer
