### ISSUE TITLE
GitHub URL validator different from server validator

### ISSUE THREAD

**Issue by serverwentdown** [fossasia/open-event-server#7401] opened 2020-03-14 10:24 UTC
**Describe the bug**

The GitHub Profile validator is different from the server implementation: entering "github.com/profile" is valid on the frontend but throws a server error on the server, without explanation. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Register for an event
2. Enter a URL without "https://"
3. Frontend says it's valid
4. Submit the form
5. A server error occurs

**Expected behaviour**

Either
- the frontend shows URLs without "https://" as invalid
- or the backend allows URLs without "https://"

**Screenshots**
![Screenshot_20200314-182752](https://user-images.githubusercontent.com/1705906/76680218-c7c8c900-6621-11ea-93bc-260014de3f16.png)

**Comment by iamareebjamal** [comment] 2020-11-01 19:39
Duplicate of #6765

**Closed by iamareebjamal** 2020-11-01 19:39 UTC
