### ISSUE TITLE
Implementing Checks on Number of Discounted and Access Code Tickets

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-server#5876] opened 2019-05-12 22:48 UTC
Parent Issue - : #5874 

**Additional Information**

Implement a Server Side Check on Number of Discounted `Tickets/Access Tickets` User enters

Working On It

**Comment by mrsaicharan1** [comment] 2019-05-13 04:41
Duplicate of #5865. Please close.

**Comment by mrsaicharan1** [comment] 2019-05-13 04:44
@kushthedude Also, please try to check if this has **already been implemented/an issue has been opened** for this already. There is a method which has been implemented to check this and we need to take a closer look at it. This is the main reason why the tests were failing for #5786

**Closed** 2019-05-13 07:51 UTC

**Comment by kushthedude** [comment] 2019-05-13 08:39
@mrsaicharan1 didnt look close before opening , will take care
