### ISSUE TITLE
Login with google not working.

### ISSUE THREAD

**Issue by khansultan1** [fossasia/open-event-server#5380] opened 2018-09-18 08:52 UTC
Trying to login with google but having some trouble can anyone  look around it. please find the screenshot for more.
![image](https://user-images.githubusercontent.com/6906715/45675945-31136d00-bb4e-11e8-8fb5-332c39427def.png)

**Comment by Ananthavijay** [comment] 2018-09-20 08:43
@khansultan1 there is a similar issue already opened. Link - https://github.com/fossasia/open-event-server/issues/5362

**Comment by bhaveshAn** [comment] 2018-09-26 16:14
@open-event-bot move to fossasia/open-event-legacy

**Comment by bhaveshAn** [comment] 2018-09-26 16:17
Duplicate of https://github.com/fossasia/open-event-server/issues/5362 hence closing

**Closed by bhaveshAn** 2018-09-26 16:17 UTC
