### ISSUE TITLE
Internal Server Error : Google OAuth Signin

### ISSUE THREAD

**Issue by himanshu-dixit** [fossasia/open-event-server#5387] opened 2018-09-28 09:45 UTC
**Describe the bug**
While using Sign in with Google, I encountered Internal Server Error.

**To Reproduce**
1. Signin with google
2. Authorize access
3. Error is presented

**Expected behavior**
Account is created or user is logged in.

**Stacktrace**
<img width="1477" alt="screenshot 2018-09-28 at 3 13 41 pm" src="https://user-images.githubusercontent.com/6849438/46201278-41d39800-c331-11e8-858a-adb4986ca7c3.png">

**Additional details (please complete the following information):**
- Not relevant. 

**Additional context**

**Comment by bhaveshAn** [comment] 2018-09-30 10:10
Duplicate of https://github.com/fossasia/open-event-server/issues/5362 hence closing

**Closed by bhaveshAn** 2018-09-30 10:10 UTC
