### ISSUE TITLE
requests.exceptions.ConnectionError when running on localhost

### ISSUE THREAD

**Issue by Batey96** [fossasia/open-event-server#6539] opened 2019-10-19 10:50 UTC
**Describe the bug**

When on localhost and disconnected from the internet,a connection error occurs..If so why put it on localhost?
**To Reproduce**
switch off internet and rerun server
python3 manage.py runserver

![runsere](https://user-images.githubusercontent.com/24868289/67143753-74b33b80-f266-11e9-83e5-bc84d7f6f6b9.png)

**Comment by iamareebjamal** [comment] 2019-10-19 12:19
The API is usable. Only the docs are not available, which is tracked in other issue #4548

**Comment by iamareebjamal** [comment] 2019-10-19 12:19
Duplicate of #4548

**Closed by iamareebjamal** 2019-10-19 12:19 UTC
