### ISSUE TITLE
Populate event locations with most frequent locations routinely

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#6054] opened 2019-06-17 11:00 UTC
Parent issue https://github.com/fossasia/open-event-frontend/issues/2970

Event locations endpoint should return the most popular locations for events, and be updated regularly.

**Comment by prateekj117** [comment] 2019-06-17 11:03
@CosmicCoder96 I will take this one. Closed the old one  (https://github.com/fossasia/open-event-server/pull/5982). Will open a new one by tonight.

**Comment by prateekj117** [comment] 2019-06-17 11:04
Also, this is a duplicate of https://github.com/fossasia/open-event-server/issues/5945

**Comment by CosmicCoder96** [comment] 2019-06-17 12:00
@prateekj117 
![image](https://user-images.githubusercontent.com/17252805/59602883-8363d780-913a-11e9-9b5d-41c5c82af4c6.png)
That means I am working on this.

**Comment by prateekj117** [comment] 2019-06-17 12:04
@CosmicCoder96 Wanted to work on it. No issue. 😅

**Comment by CosmicCoder96** [comment] 2019-06-17 12:15
Yeah, I figured but had already started working on it :) after self
assigning.

**Closed** 2019-06-18 19:58 UTC
Labels: feature, sub issue
