### ISSUE TITLE
[BUGS] Dates Not Validated, Broken URL in languages other than English, Broken Sharing Methods

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/open-event-server#4594] opened 2018-01-09 21:42 UTC
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
- Dates not validated
![image](https://user-images.githubusercontent.com/14032427/34744126-2c26f4a4-f5b2-11e7-966c-60b1fdb9257c.png)

The day names are compared and rendered as strings, and not validated.

- Cannot share event on details page
![image](https://user-images.githubusercontent.com/14032427/34744227-83c608e4-f5b2-11e7-8b2a-79f9408a6f73.png)
Share buttons missing ?

- Page not found on sharing on facebook 
![image](https://user-images.githubusercontent.com/14032427/34744274-b49652a8-f5b2-11e7-8ef3-487601dd3edd.png)
![image](https://user-images.githubusercontent.com/14032427/34744291-bf78509a-f5b2-11e7-81bf-02adf4d65cca.png)

- Page not found on sharing on google plus
![image](https://user-images.githubusercontent.com/14032427/34744354-f2ba9864-f5b2-11e7-8ada-466a280cf9e8.png)

- Non English URL Support missing. (causes above mentioned 2 issues)

- Cannot log in using Google or Facebook. 

**Expected behavior:**
- Smooth sharing
- No errors in links

**Steps to reproduce:**
- Convert URLs to utf
- Fix social integration
**not sure about them the utf thing**

**Other information:**
https://stackoverflow.com/questions/6515781/can-we-have-a-language-other-than-english-in-a-url

**System**
```
Google Chrome on Windows 8.1 64x,
AMD A4 Quad Core, 2.2GHz
4 GB DDR3 Memory
Intel Network Card 
(last 3 don't even matter but looks geeky)
```

**Comment by shubham-padia** [comment] 2018-01-28 19:38
Duplicate of #4562

**Closed by shubham-padia** 2018-01-28 19:38 UTC
