### ISSUE TITLE
Server returns 409 : Ticket already sold out, even though tickets are remaining

### ISSUE THREAD

**Issue by CosmicCoder96** [fossasia/open-event-server#6433] opened 2019-08-29 07:34 UTC
![image](https://user-images.githubusercontent.com/17252805/63919905-a8fc3f80-ca0d-11e9-9dc3-a50b20b31769.png)
{"errors": [{"status": 409, "source": {"pointer": "/data/attributes/ticket_id"}, "title": "Conflict", "detail": "Ticket already sold out"}], "jsonapi": {"version": "1.0"}}

Either the statistic is incorrect on frontend or it's wrong on the server.

**Comment by iamareebjamal** [comment] 2019-12-12 14:32
Duplicate of #6653

**Closed by iamareebjamal** 2019-12-12 14:32 UTC
