### ISSUE TITLE
Wrong method provided in Events API docs to set event_topic_id

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-server#4950] opened 2018-06-21 21:14 UTC
**Describe the bug**
The event_topic_id field for setting the event topic for an event is actually of no use and doesn't work.
We add relationship with event topic to an event for that to work. The field should be removed from the docs :+1:

**Comment by srv-twry** [comment] 2018-06-25 13:13
This is just to read the `event_topic_id`, not to set it. 
> We add relationship with event topic to an event for that to work. 

yes, that's the only way to do it. it's not a bug and not an issue with the docs also. closing this one. Feel free to reopen if you don't agree with this.

**Closed by srv-twry** 2018-06-25 13:13 UTC

**Comment by dreadpool2** [comment] 2018-06-25 13:15
Cool :+1:
