### ISSUE TITLE
Invitation link cause an error

### ISSUE THREAD

**Issue by mishari** [fossasia/open-event-server#6823] opened 2020-02-08 05:52 UTC
**Describe the bug**
I received an invitation link to be coorganizer. When I click on the link I get this error:

**To Reproduce**
Click on co-organizer invite link in email, login, click on link again.

**Expected behavior**
I'm expecting to use my existing credentials to be a co-organizer.

**Stacktrace**
Error: TransitionAborted
    at e (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:3545:35)
    at E (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:5363:12)
    at _ (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:5361:128)
    at g (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:5359:107)
    at t.invokeWithOnError (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:4897:242)
    at e.t.flush (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:4889:74)
    at e.t.flush (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:4903:207)
    at e.n._end (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:4965:9)
    at _boundAutorunEnd (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:4915:574)
    at a (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:1324:61)
    at /fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:1324:206
    at u (/fastboot/dist/assets/vendor-82870f06c3225516c5251c90cb87c51a.js:1018:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Additional details (please complete the following information):**
MacOS
Firefox 72.0.2

**Additional context**

**Comment by iamareebjamal** [comment] 2020-02-08 08:37
Duplicate of https://github.com/fossasia/open-event-frontend/issues/3347

**Closed by iamareebjamal** 2020-02-08 08:37 UTC
