### ISSUE TITLE
`PATCH` API for video_channel is not working

### ISSUE THREAD

**Issue by minhho89** [fossasia/open-event-server#9024] opened 2023-07-31 15:18 UTC
**Describe the bug**
The `PATCH` API of `v1/translation_channels?` keeps throwing `404 NOT FOUND`

**To Reproduce**
1. Go to `Manange Event`
2. Choose some event to test, click on `Event Dashboard`
<img width="408" alt="image" src="https://github.com/fossasia/open-event-server/assets/61931543/323adebf-a62e-40df-8f28-c3947ee6b789">

3. Move to `Video` tab
4. Choose a Video Room, click `edit` button to go to the `Video Channel` page
5. Click to `Add Channel`, input some URL and choose a language and click the button with the Add icon
6. Save
7. Go back to the `Video Channel` page, edit the newly added channel, and click the Add icon again, this shall send the Patch API. Use `Network` tab in the browser `Devtool` to check the error

**Expected behavior**
The PATCH API should have an OK response and the channel information is edited

**Comment by mariobehling** [comment] 2023-07-31 16:41
Duplicate of https://github.com/fossasia/open-event-server/issues/9019

Added this as a comment there.

**Closed by mariobehling** 2023-07-31 16:41 UTC
