### ISSUE TITLE
Unable to run create_db.py

### ISSUE THREAD

**Issue by tjwebb** [fossasia/open-event-server#6603] opened 2019-11-17 22:40 UTC
**Describe the bug**
I cannot successfully execute create_db.py

**To Reproduce**
Set all the postgres variables, and run create_db.py

**Expected behavior**
I expected to not get an error

**Stacktrace**
```
$ python3 create_db.py 
Traceback (most recent call last):
  File "create_db.py", line 7, in <module>
    from app import current_app
  File "/home/me/open-event-server/app/__init__.py", line 36, in <module>
    from app.api.helpers.jwt import jwt_user_loader
  File "/home/me/open-event-server/app/api/__init__.py", line 1, in <module>
    from app.api.access_codes import AccessCodeList, AccessCodeListPost, AccessCodeDetail, AccessCodeRelationshipRequired, \
  File "/home/me/open-event-server/app/api/access_codes.py", line 5, in <module>
    from app.api.bootstrap import api
  File "/home/me/open-event-server/app/api/bootstrap.py", line 3, in <module>
    from app.api.helpers.permission_manager import permission_manager
  File "/home/me/open-event-server/app/api/helpers/permission_manager.py", line 9, in <module>
    from app.models.event import Event
  File "/home/me/open-event-server/app/models/event.py", line 19, in <module>
    from app.models.search import sync
  File "/home/me/open-event-server/app/models/search/sync.py", line 11, in <module>
    from app.models.search.event import SearchableEvent
  File "/home/me/open-event-server/app/models/search/event.py", line 2, in <module>
    from elasticsearch_dsl import DocType, Integer, Search, Text
ImportError: cannot import name 'DocType' from 'elasticsearch_dsl' (/usr/local/lib/python3.7/site-packages/elasticsearch_dsl/__init__.py)
```
**Additional details (please complete the following information):**
 - OS: Linux `cs-6000-devshell-vm-04afeef9-07a4-45af-bb01-74a7d90eb826 4.19.72+ #1 SMP Thu Nov 7 22:31:52 PST 2019 x86_64 GNU/Linux`

 - Python Version: 3.7.3
 - `HEAD` Commit hash v1.7.0 tag

**Additional context**

**Comment by tjwebb** [comment] 2019-11-17 22:45
I found this issue: https://github.com/sabricot/django-elasticsearch-dsl/issues/119

I updated `requirements/common.txt` to use this version of elasticsearch: `elasticsearch-dsl~=6.1.0`, and the script ran successfully.

**Comment by iamareebjamal** [comment] 2019-11-17 23:48
Duplicate of #6560

**Closed by iamareebjamal** 2019-11-17 23:48 UTC

**Comment by iamareebjamal** [comment] 2019-11-17 23:52
Please pull latest changes and retry
