### ISSUE TITLE
Urls like original-image-url get changed after creating events using API

### ISSUE THREAD

**Issue by dreadpool2** [fossasia/open-event-server#5307] opened 2018-08-07 16:32 UTC
**Describe the bug**
Urls like `originial-image-url`are getting changed in the response shown after using POST request to create them. API used `api.eventyay.com/v1/events`. Below is the event to be posted raw data and corresponding response.

Event to be posted:-
```
{
  "data": {
    "attributes": {
      "name": "Music & Voice Therapy with Michele Chong",
      "external-event-url": "http://example.com",
      "starts-at": "2018-10-12T23:59:59.123456+00:00",
      "ends-at": "2018-10-20T23:59:59.123456+00:00",
      "timezone": "UTC",
      "latitude": "1.29456789",
      "longitude": "103.85",
      "logo-url": "https://upload.wikimedia.org/wikipedia/commons/8/88/Music-segno.png",
      "location-name": "Raffles Place, Singapore",
      "searchable-location-name": "Singapore",
      "description": "An oft cited notable example of the dilemma in defining music is a work entitled 4'33'' (1952) by the American composer John Cage (1912–1992). The written score has three movements and directs the performer(s) to appear on stage, indicate by gesture or other means when the piece begins, then make no sound and only mark sections and the end by gesture. What is heard are only whatever ambient sounds may occur in the room. Some argue this is not music because, for example, it contains no sounds that are conventionally considered musical",
      "original-image-url": "https://steemitimages.com/DQmWG96SKvDEx98pB4T34CB7UqgkZDRawHNaDsoETzLmQ57/1240e483-c8b9-4d0d-8b48-c8c245f2c05e.jpg",
      "organizer-name": "Musical Organizers",
      "is-map-shown": "true",
      "organizer-description": "Good Organizer!",
      "is-sessions-speakers-enabled": "true",
      "privacy": "public",
      "state": "draft",
      "average-rating": null,
      "ticket-url": "http://example.com",
      "code-of-conduct": "example",
      "is-ticketing-enabled": "true",
      "payment-country": "US",
      "payment-currency": "USD",
      "paypal-email": "example@example.com",
      "is-tax-enabled": "true",
      "can-pay-by-paypal": "true",
      "can-pay-by-stripe": "true",
      "can-pay-by-cheque": "true",
      "can-pay-by-bank": "true",
      "can-pay-onsite": "true",
      "cheque-details": "example",
      "bank-details": "example",
      "onsite-details": "example",
      "is-sponsors-enabled": "false",
      "has-organizer-info": "false",
      "order-expiry-time": "10"
    },
    "type": "event"
  }
}
```

Response:-

```
{
    "data": {
        "type": "event",
        "attributes": {
            "can-pay-by-stripe": true,
            "organizer-description": "Good Organizer!",
            "schedule-published-on": null,
            "cheque-details": "example",
            "state": "draft",
            "thumbnail-image-url": "http://localhost:5000/static/media/events/11/thumbnail/aGdud2NMcT/c1449a43-ca6b-42c3-ada7-e357ac6b21b5.jpg",
            "location-name": "Raffles Place, Singapore",
            "organizer-name": "Musical Organizers",
            "can-pay-by-bank": true,
            "starts-at": "2018-10-12T23:59:59.123456+00:00",
            "timezone": "UTC",
            "is-sponsors-enabled": false,
            "can-pay-by-paypal": true,
            "large-image-url": "http://localhost:5000/static/media/events/11/large/QXN6enM3Nj/f3ddb7c7-f036-443f-aca6-feb18a968a03.jpg",
            "has-organizer-info": false,
            "is-map-shown": true,
            "original-image-url": "http://localhost:5000/static/media/events/11/original/cFlISFBQb2/2eeef3bc-5b24-4b25-a094-616ced922432.jpg",
            "ticket-url": "http://example.com",
            "icon-image-url": "http://localhost:5000/static/media/events/11/icon/cFhCcnBiRV/fc2d8186-c9ff-4fc7-a723-87a21c34808d.jpg",
            "xcal-url": null,
            "onsite-details": "example",
            "average-rating": null,
            "identifier": "b5f87a50",
            "latitude": 1.29456789,
            "is-sessions-speakers-enabled": true,
            "pentabarf-url": null,
            "code-of-conduct": "example",
            "is-ticketing-enabled": true,
            "bank-details": "example",
            "longitude": 103.85,
            "external-event-url": "http://example.com",
            "ical-url": null,
            "searchable-location-name": "Singapore",
            "can-pay-by-cheque": true,
            "paypal-email": "example@example.com",
            "ends-at": "2018-10-20T23:59:59.123456+00:00",
            "privacy": "public",
            "payment-currency": "USD",
            "name": "Music & Voice Therapy with Michele Chong",
            "deleted-at": null,
            "logo-url": "https://upload.wikimedia.org/wikipedia/commons/8/88/Music-segno.png",
            "is-tax-enabled": true,
            "payment-country": "US",
            "can-pay-onsite": true,
            "description": "An oft cited notable example of the dilemma in defining music is a work entitled 4'33'' (1952) by the American composer John Cage (1912–1992). The written score has three movements and directs the performer(s) to appear on stage, indicate by gesture or other means when the piece begins, then make no sound and only mark sections and the end by gesture. What is heard are only whatever ambient sounds may occur in the room. Some argue this is not music because, for example, it contains no sounds that are conventionally considered musical",
            "created-at": "2018-08-07T15:27:14.583517+00:00"
        },
        "relationships": {
            "tickets": {
                "links": {
                    "self": "/v1/events/11/relationships/tickets",
                    "related": "/v1/events/11/tickets"
                }
            },
            "sessions": {
                "links": {
                    "self": "/v1/events/11/relationships/sessions",
                    "related": "/v1/events/11/sessions"
                }
            },
            "speakers": {
                "links": {
                    "self": "/v1/events/11/relationships/speakers",
                    "related": "/v1/events/11/speakers"
                }
            },
            "moderators": {
                "links": {
                    "self": "/v1/events/11/relationships/moderators",
                    "related": "/v1/users"
                }
            },
            "registrars": {
                "links": {
                    "self": "/v1/events/11/relationships/registrars",
                    "related": "/v1/users"
                }
            },
            "event-topic": {
                "links": {
                    "self": "/v1/events/11/relationships/event-topic",
                    "related": "/v1/events/11/event-topic"
                }
            },
            "stripe-authorization": {
                "links": {
                    "self": "/v1/stripe-authorizations/11/relationships/event",
                    "related": "/v1/events/11/stripe-authorization"
                }
            },
            "role-invites": {
                "links": {
                    "self": "/v1/events/11/relationships/role-invites",
                    "related": "/v1/events/11/role-invites"
                }
            },
            "orders": {
                "links": {
                    "self": "/v1/events/11/relationships/orders",
                    "related": "/v1/events/11/orders"
                }
            },
            "sponsors": {
                "links": {
                    "self": "/v1/events/11/relationships/sponsors",
                    "related": "/v1/events/11/sponsors"
                }
            },
            "discount-codes": {
                "links": {
                    "self": "/v1/events/11/relationships/discount-codes",
                    "related": "/v1/events/11/discount-codes"
                }
            },
            "event-sub-topic": {
                "links": {
                    "self": "/v1/events/11/relationships/event-sub-topic",
                    "related": "/v1/events/11/event-sub-topic"
                }
            },
            "social-links": {
                "links": {
                    "self": "/v1/events/11/relationships/social-links",
                    "related": "/v1/events/11/social-links"
                }
            },
            "event-type": {
                "links": {
                    "self": "/v1/events/11/relationships/event-type",
                    "related": "/v1/events/11/event-type"
                }
            },
            "event-invoices": {
                "links": {
                    "self": "/v1/events/11/relationships/event-invoices",
                    "related": "/v1/events/11/event-invoices"
                }
            },
            "access-codes": {
                "links": {
                    "self": "/v1/events/11/relationships/access-codes",
                    "related": "/v1/events/11/access-codes"
                }
            },
            "faq-types": {
                "links": {
                    "self": "/v1/events/11/relationships/faq-types",
                    "related": "/v1/events/11/faq-types"
                }
            },
            "speakers-call": {
                "links": {
                    "self": "/v1/events/11/relationships/speakers-call",
                    "related": "/v1/events/11/speakers-call"
                }
            },
            "faqs": {
                "links": {
                    "self": "/v1/events/11/relationships/faqs",
                    "related": "/v1/events/11/faqs"
                }
            },
            "tax": {
                "links": {
                    "self": "/v1/events/11/relationships/tax",
                    "related": "/v1/events/11/tax"
                }
            },
            "event-copyright": {
                "links": {
                    "self": "/v1/events/11/relationships/event-copyright",
                    "related": "/v1/events/11/event-copyright"
                }
            },
            "custom-forms": {
                "links": {
                    "self": "/v1/events/11/relationships/custom-forms",
                    "related": "/v1/events/11/custom-forms"
                }
            },
            "attendees": {
                "links": {
                    "self": "/v1/events/11/relationships/attendees",
                    "related": "/v1/events/11/attendees"
                }
            },
            "tracks": {
                "links": {
                    "self": "/v1/events/11/relationships/tracks",
                    "related": "/v1/events/11/tracks"
                }
            },
            "ticket-tags": {
                "links": {
                    "self": "/v1/events/11/relationships/ticket-tags",
                    "related": "/v1/events/11/ticket-tags"
                }
            },
            "coorganizers": {
                "links": {
                    "self": "/v1/events/11/relationships/coorganizers",
                    "related": "/v1/users"
                }
            },
            "feedbacks": {
                "links": {
                    "self": "/v1/events/11/relationships/feedbacks",
                    "related": "/v1/events/11/feedbacks"
                }
            },
            "track-organizers": {
                "links": {
                    "self": "/v1/events/11/relationships/track-organizers",
                    "related": "/v1/users"
                }
            },
            "microlocations": {
                "links": {
                    "self": "/v1/events/11/relationships/microlocations",
                    "related": "/v1/events/11/microlocations"
                }
            },
            "organizers": {
                "links": {
                    "self": "/v1/events/11/relationships/organizers",
                    "related": "/v1/users"
                }
            },
            "session-types": {
                "links": {
                    "self": "/v1/events/11/relationships/session-types",
                    "related": "/v1/events/11/session-types"
                }
            }
        },
        "id": "11",
        "links": {
            "self": "/v1/events/11"
        }
    },
    "links": {
        "self": "/v1/events/11"
    },
    "jsonapi": {
        "version": "1.0"
    }
}
```

**Comment by bhaveshAn** [comment] 2018-08-07 16:40
Not a issue. It is because after getting the image url it first sets it into different sizes and get stored in static directory. And then fetches the url of local image in static dir.

**Comment by dreadpool2** [comment] 2018-08-07 16:42
But hen how can we show these images in the app? As these links depend on local host

**Comment by dreadpool2** [comment] 2018-08-07 17:08
@bhaveshAn It's working perfectly fine when we use api `https://open-event-api-dev.herokuapp.com/v1/events` but not when `api.eventyay.com/v1/events` is used

**Comment by bhaveshAn** [comment] 2018-08-07 17:17
Check http://api.eventyay.com/static/media/events/11/icon/cFhCcnBiRV/fc2d8186-c9ff-4fc7-a723-87a21c34808d.jpg

**Comment by bhaveshAn** [comment] 2018-08-07 17:18
Changing `localhost:5000` to `api.eventyay.com` works

**Comment by dreadpool2** [comment] 2018-08-07 17:27
Isn't it a server bug then? You are returning the correct url while using the heroku API but not while using eventyay? Do correct me if I am wrong.

**Comment by bhaveshAn** [comment] 2018-08-07 20:01
You are right. Do you wanna work on this ??

**Comment by bhaveshAn** [comment] 2018-08-10 12:18
Sure !

**Comment by iamareebjamal** [comment] 2019-04-10 08:54
This is still a concern AFAIK

**Comment by uds5501** [comment] 2019-04-24 09:00
@iamareebjamal will #5330 resolve the issue?

**Comment by iamareebjamal** [comment] 2019-04-24 19:26
But it is closed. If the issue it was addressing is fixed, then yes

**Comment by uds5501** [comment] 2019-04-25 01:17
@iamareebjamal This issue has been resolved already. The original image url is being returned as required.

```
{
    "links": {
        "self": "/v1/events/9"
    },
    "jsonapi": {
        "version": "1.0"
    },
    "data": {
        "links": {
            "self": "/v1/events/9"
        },
        "attributes": {
            "payment-currency": "USD",
            "can-pay-by-cheque": true,
            "paypal-email": "example@example.com",
            "can-pay-onsite": true,
            "is-event-online": false,
            "onsite-details": "example",
            "searchable-location-name": "Singapore",
            "can-pay-by-bank": true,
            "state": "draft",
            "deleted-at": null,
            "has-organizer-info": false,
            "icon-image-url": null,
            "average-rating": null,
            "payment-country": "US",
            "description": "An oft cited notable example of the dilemma in defining music is a work entitled 4'33'' (1952) by the American composer John Cage (1912–1992). The written score has three movements and directs the performer(s) to appear on stage, indicate by gesture or other means when the piece begins, then make no sound and only mark sections and the end by gesture. What is heard are only whatever ambient sounds may occur in the room. Some argue this is not music because, for example, it contains no sounds that are conventionally considered musical",
            "thumbnail-image-url": null,
            "xcal-url": null,
            "has-speakers": false,
            "is-ticketing-enabled": true,
            "is-tax-enabled": true,
            "refund-policy": "All sales are final. No refunds shall be issued in any case.",
            "is-donation-enabled": false,
            "tickets-sold": 0,
            "can-pay-by-paypal": true,
            "is-map-shown": true,
            "ticket-url": "http://example.com",
            "logo-url": "https://upload.wikimedia.org/wikipedia/commons/8/88/Music-segno.png",
            "organizer-description": "Good Organizer!",
            "location-name": "Raffles Place, Singapore",
            "timezone": "UTC",
            "pentabarf-url": null,
            "revenue": 0,
            "latitude": 1.29456789,
            "longitude": 103.85,
            "original-image-url": "https://steemitimages.com/DQmWG96SKvDEx98pB4T34CB7UqgkZDRawHNaDsoETzLmQ57/1240e483-c8b9-4d0d-8b48-c8c245f2c05e.jpg",
            "is-stripe-linked": false,
            "code-of-conduct": "example",
            "ical-url": null,
            "privacy": "public",
            "can-pay-by-stripe": true,
            "organizer-name": "Musical Organizers",
            "order-expiry-time": 10,
            "bank-details": "example",
            "ends-at": "2019-10-20T23:59:59.123456+00:00",
            "large-image-url": null,
            "external-event-url": "http://example.com",
            "is-sponsors-enabled": false,
            "is-featured": false,
            "name": "Music & Voice Therapy with Michele Chong",
            "has-sessions": false,
            "created-at": "2019-04-25T01:15:00.023651+00:00",
            "starts-at": "2019-10-12T23:59:59.123456+00:00",
            "schedule-published-on": null,
            "identifier": "ba7a0297",
            "cheque-details": "example",
            "tickets-available": 0,
            "is-sessions-speakers-enabled": true
        },
        "type": "event",
        "relationships": {
            "event-invoices": {
                "links": {
                    "self": "/v1/events/9/relationships/event-invoices",
                    "related": "/v1/events/9/event-invoices"
                }
            },
            "tickets": {
                "links": {
                    "self": "/v1/events/9/relationships/tickets",
                    "related": "/v1/events/9/tickets"
                }
            },
            "orders": {
                "links": {
                    "self": "/v1/events/9/relationships/orders",
                    "related": "/v1/events/9/orders"
                }
            },
            "session-types": {
                "links": {
                    "self": "/v1/events/9/relationships/session-types",
                    "related": "/v1/events/9/session-types"
                }
            },
            "access-codes": {
                "links": {
                    "self": "/v1/events/9/relationships/access-codes",
                    "related": "/v1/events/9/access-codes"
                }
            },
            "track-organizers": {
                "links": {
                    "self": "/v1/events/9/relationships/track-organizers",
                    "related": "/v1/users"
                }
            },
            "faqs": {
                "links": {
                    "self": "/v1/events/9/relationships/faqs",
                    "related": "/v1/events/9/faqs"
                }
            },
            "custom-forms": {
                "links": {
                    "self": "/v1/events/9/relationships/custom-forms",
                    "related": "/v1/events/9/custom-forms"
                }
            },
            "faq-types": {
                "links": {
                    "self": "/v1/events/9/relationships/faq-types",
                    "related": "/v1/events/9/faq-types"
                }
            },
            "event-orga": {
                "links": {
                    "self": "/v1/events/9/relationships/event-orga",
                    "related": "/v1/events/9/event-orga"
                }
            },
            "tracks": {
                "links": {
                    "self": "/v1/events/9/relationships/tracks",
                    "related": "/v1/events/9/tracks"
                }
            },
            "event-type": {
                "links": {
                    "self": "/v1/events/9/relationships/event-type",
                    "related": "/v1/events/9/event-type"
                }
            },
            "ticket-tags": {
                "links": {
                    "self": "/v1/events/9/relationships/ticket-tags",
                    "related": "/v1/events/9/ticket-tags"
                }
            },
            "coorganizers": {
                "links": {
                    "self": "/v1/events/9/relationships/coorganizers",
                    "related": "/v1/users"
                }
            },
            "tax": {
                "links": {
                    "self": "/v1/events/9/relationships/tax",
                    "related": "/v1/events/9/tax"
                }
            },
            "social-links": {
                "links": {
                    "self": "/v1/events/9/relationships/social-links",
                    "related": "/v1/events/9/social-links"
                }
            },
            "moderators": {
                "links": {
                    "self": "/v1/events/9/relationships/moderators",
                    "related": "/v1/users"
                }
            },
            "speakers-call": {
                "links": {
                    "self": "/v1/events/9/relationships/speakers-call",
                    "related": "/v1/events/9/speakers-call"
                }
            },
            "event-topic": {
                "links": {
                    "self": "/v1/events/9/relationships/event-topic",
                    "related": "/v1/events/9/event-topic"
                }
            },
            "microlocations": {
                "links": {
                    "self": "/v1/events/9/relationships/microlocations",
                    "related": "/v1/events/9/microlocations"
                }
            },
            "attendees": {
                "links": {
                    "self": "/v1/events/9/relationships/attendees",
                    "related": "/v1/events/9/attendees"
                }
            },
            "discount-codes": {
                "links": {
                    "self": "/v1/events/9/relationships/discount-codes",
                    "related": "/v1/events/9/discount-codes"
                }
            },
            "organizers": {
                "links": {
                    "self": "/v1/events/9/relationships/organizers",
                    "related": "/v1/users"
                }
            },
            "sponsors": {
                "links": {
                    "self": "/v1/events/9/relationships/sponsors",
                    "related": "/v1/events/9/sponsors"
                }
            },
            "feedbacks": {
                "links": {
                    "self": "/v1/events/9/relationships/feedbacks",
                    "related": "/v1/events/9/feedbacks"
                }
            },
            "event-copyright": {
                "links": {
                    "self": "/v1/events/9/relationships/event-copyright",
                    "related": "/v1/events/9/event-copyright"
                }
            },
            "role-invites": {
                "links": {
                    "self": "/v1/events/9/relationships/role-invites",
                    "related": "/v1/events/9/role-invites"
                }
            },
            "registrars": {
                "links": {
                    "self": "/v1/events/9/relationships/registrars",
                    "related": "/v1/users"
                }
            },
            "sessions": {
                "links": {
                    "self": "/v1/events/9/relationships/sessions",
                    "related": "/v1/events/9/sessions"
                }
            },
            "event-sub-topic": {
                "links": {
                    "self": "/v1/events/9/relationships/event-sub-topic",
                    "related": "/v1/events/9/event-sub-topic"
                }
            },
            "stripe-authorization": {
                "links": {
                    "self": "/v1/stripe-authorizations/9/relationships/event",
                    "related": "/v1/events/9/stripe-authorization"
                }
            },
            "speakers": {
                "links": {
                    "self": "/v1/events/9/relationships/speakers",
                    "related": "/v1/events/9/speakers"
                }
            }
        },
        "id": "9"
    }
}
```

**Comment by prateekj117** [comment] 2019-08-07 20:26
Not reproducible anymore. @iamareebjamal @uds5501 Let's close this.

**Closed** 2019-08-07 20:58 UTC
Labels: bug, deployment, has-PR
