### ISSUE TITLE
Wrong schema validation

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#4655] opened 2018-04-02 19:47 UTC
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-server

**Current behavior:**
Schema validation on the server is broken

```JSON
{
  "data": {
    "relationships": {
      "event": {
        "data": {
          "type": "event",
          "id": "{{event}}"
        }
      }
    },
    "attributes": {
      "name": "ticket-name",
      "description": "some description",
      "type": "VIP-ticket",
      "price": "100.00",
      "quantity": "100",
      "is-description-visible": null,
      "position": "1",
      "is-fee-absorbed": "false",
      "sales-starts-at": "2017-06-01T01:24:47.500127+00:00",
      "sales-ends-at": "2017-06-30T00:24:47.500127+00:00",
      "is-hidden": "false",
      "min-order": "1",
      "max-order": "100"
    },
    "type": "ticket"
  }
}
```
If any of the optional field is null (which is what it can be when serializing in Java or any other language with schema, it gives the following error

```JSON
{
    "jsonapi": {
        "version": "1.0"
    },
    "errors": [
        {
            "status": "422",
            "source": {
                "pointer": "/data/attributes/is-description-visible"
            },
            "title": "Validation error",
            "detail": "Field may not be null."
        }
    ]
}
```

However this is clearly an optional field. Also, all validation is done prematurely and before applying the default values, which is counter productive. If quantity is missing, it should be assigned the default value from the server rather than reporting `quantity should be higher than min-order`

Some of these changes in API are breaking and make it really hard developing mobile applications, because we cannot base our development on a particular API assuming it won't break any contracts. master branch is unusable so we switched to development, but it introduces several breaking changes without any communication in documentation.

Several times, the development in mobile (and I assume web) is halted with questions as we are not able to POST ticket, feedback, event because of some reason, and it prevents us to create new features or move forward in a direction we believe API will move. But we cannot because it is unpredictable what will change and how will we accomodate with it. Now we are essentially stopped in our tracks until the server is fixed because not everyone knows how to setup API locally and even if they do, they don't know which branch or commit they should target? And it might be easy to develop with local API on web, it isn't on mobile

~~I believe this is a side effect of the recent change in flask rest jsonapi, and the changes made in local fork might be necessary and convenient but they break several previously established behaviours~~. I think we should agree that APIs should conform to their users and not the other way around, so I urge the developers to ensure that any such breaking changes be well tested before merging and communicated in some form of documentation. Thanks

**Edit:** The dev branch was not deployed for a long time to heroku, so all the breaking changes throughout the months got introduced to us in last few weeks.

**Comment by shubham-padia** [comment] 2018-04-02 20:30
>  I believe this is a side effect of the recent change in flask rest jsonapi

There has been no change in the repo, it's the same as before, just the location has changed. No changes were made breaking/non-breaking

**Comment by iamareebjamal** [comment] 2018-04-02 20:37
Nevertheless, these responses are being generated on providing the input. Which wasn't the case before. Is it the expected behaviour? If so, what's the use of default fields

**Comment by shubham-padia** [comment] 2018-04-02 20:46
> Nevertheless, these responses are being generated on providing the input. Which wasn't the case before. 

There have been very few changes in the behaviour of the API in the past few months, the bug you've mentioned was pre-existing and should be fixed, but not a part of any recent changes AFAIK. For optional fields, this error should not be generated. But it would be better if the clients take active part in creating issues, there's been very few issuer reported related to the API (not including the development environment related). If anything's different from the expected behaviour, please report it.

**Comment by iamareebjamal** [comment] 2018-04-02 20:53
This was due to clients not knowing of the divergence from the master and dev branches, We only knew this when the master branch version stopped working altogether, And till a few weeks back, we were able to create tickets and events.

The developement in orga repo is very active so we would have noticed if this was very old. For instance, the event issue arose about 2-3 weeks ago and was noticed 9 days ago or so
https://github.com/fossasia/open-event-orga-app/issues/837

**Comment by iamareebjamal** [comment] 2018-04-02 20:57
Secondly, as I noticed earlier, the development branch was not even deployed to heroku for months on end, and that is why even if the changes were done months ago, we could have only noticed it when the actual deployments started happening which were 2-3 weeks back. So yes, I agree that this behaviour did not arise from the fork but API definitely introduced breaking changes and only in past weeks for us

**Comment by shubham-padia** [comment] 2018-04-02 23:45
> the development branch was not even deployed to heroku for months on end, and that is why even if the changes were done months ago, we could have only noticed it when the actual deployments started happening which were 2-3 weeks back

Yep. That sounds like the reason for the changes appearing to the clients

**Comment by srv-twry** [comment] 2018-04-19 00:55
@iamareebjamal Can i work on it ?

**Comment by iamareebjamal** [comment] 2018-04-19 10:05
@srv-twry Please go ahead

**Comment by srv-twry** [comment] 2018-04-20 05:48
@iamareebjamal @shubham-padia 
I understood the problem and have a proposed solution.
Going through the marshmallow docs, i found that they allow data preprocessing before loading(validation) of the data by defining methods with decorators ```pre_load```.
Reference [here](http://marshmallow.readthedocs.io/en/latest/extending.html#extending)

So the solution could be to define a function in the schema files for each Model which would set all the ```None``` values to its default values before loading.

For eg. 
``` Python
@pre_load
def set_default_to_none(self, data):
    if data.get('is-description-visible') is None:
        data['is-description-visible'] = DESCRIPTION_VISIBLE_DEFAULT
```

fixes the given problem.
We could define a dictionary of default values and use it in this method for schema's with a lot of default values.
Is it the right approach or do you have any suggested way ?

**Comment by iamareebjamal** [comment] 2018-04-20 07:01
The default values are already given when declaring the schema, I think this will be code duplication

**Comment by srv-twry** [comment] 2018-04-20 12:43
@iamareebjamal 
Using this would mean i would have to make sure the variable names match the key in the ```in_data``` variable. For eg. in the ```in_data``` dictionary the description visibility boolean has the key ```is-description-visible``` while the variable name  in python is ```is_description_visible```. 
I would have to change the variable name to ```is-description-visible``` which is not allowed.

One way would be to have a dictionary which maps the variable name to corresponding key names i.e. 
``` Python
{
    IS_DESCRIPTION_VISIBLE_KEY = 'is-description-visible',
    ...
}
```

**Comment by iamareebjamal** [comment] 2018-04-20 13:15
look at the function dasherize

**Comment by srv-twry** [comment] 2018-04-20 14:58
``` Python
    def make_object(self, in_data):
        for name, field in self.fields.items():
            if not in_data.get('data').get('attributes').get(dasherize(name)):
                in_data['data']['attributes'][dasherize(name)] = field.default
        return in_data
```

Adding this method to Ticket schema class works. Is it okay ? If it is i would add this to all the schema classes and send the PR.

**Comment by srv-twry** [comment] 2018-04-21 03:54
@iamareebjamal 
1. I forgot to add the ```@pre-load``` in the comment above. Updated it. The ```make_object``` isn't called automatically, so i had to annotate it. It isn't called automatically probably because it's depricated now as you can see [here](http://marshmallow.readthedocs.io/en/latest/upgrading.html?highlight=make_object) and [here](https://github.com/marshmallow-code/marshmallow/issues/277)

 > Create a util function in utils/common.py (new file) and use that method instead.

2. I am not sure how to implement it. AFAIK we are using the ```flask_rest_jsonapi``` library to handle the requests. I cannot make any changes to its source code. So how would i call the util function that you want me to add ?
Here is the method of the library that handles the post requests
``` Python
@check_method_requirements
    def post(self, *args, **kwargs):
        """Create an object
        """
        json_data = request.get_json()

        qs = QSManager(request.args, self.schema)

        schema = compute_schema(self.schema,
                                getattr(self, 'post_schema_kwargs', dict()),
                                qs,
                                qs.include)

        try:
            data, errors = schema.load(json_data)
        except IncorrectTypeError as e:
            errors = e.messages
            for error in errors['errors']:
                error['status'] = '409'
                error['title'] = "Incorrect type"
            return errors, 409
        except ValidationError as e:
            errors = e.messages
            for message in errors['errors']:
                message['status'] = '422'
                message['title'] = "Validation error"
            return errors, 422

        if errors:
            for error in errors['errors']:
                error['status'] = "422"
                error['title'] = "Validation error"
            return errors, 422

        self.before_post(args, kwargs, data=data)

        obj = self._data_layer.create_object(data, kwargs)

        result = schema.dump(obj).data
        self.after_post(result)
        return result, 201, {'Location': result['data']['links']['self']}
```
I would have to call the util function before the ```try-except``` block.

**Comment by iamareebjamal** [comment] 2018-04-21 04:55
I meant this

``` Python
    from utils.common import patch_defaults

    @pre_load
    def make_object(self, in_data):
        return patch_defaults(self, in_data)
```

```python
    def patch_defaults(schema, in_data):
        data = in_data.get('data')
        if data is None or data.get('attributes') is None:
            return in_data
        attributes = data.get('attributes')
        for name, field in schema.fields.items():
            dasherized_name = dasherize(name)
            attribute = attributes.get(dasherized_name)
            if attribute is None:
                attributes[dasherized_name] = field.default
        return in_data
```

**Comment by iamareebjamal** [comment] 2018-04-21 04:58
And you can also make a class decorator, which adds this function on the class automatically

**Closed** 2018-05-16 11:07 UTC
Labels: bug, has-PR
